# -*- coding: utf-8 -*-
"""HashingDalamPython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cO85eB8YShCchmaS5-A3XrnJPQy8pxwK

1. Implementasi Hash Table Sederhana
"""

class SimpleHashTable:
  def __init__(self, size):
    self.size = size
    self.table = [None] * size

  def hash_function(self, key):
    return hash(key) % self.size

  def insert(self, key, value):
    index = self.hash_function(key)
    self.table[index] = value

  def search(self, key):
    index = self.hash_function(key)
    return self.table[index]

ht = SimpleHashTable(10)
ht.insert("apel", 100)
ht.insert("pisang", 200)

print("Nilai untuk 'apel':", ht.search("apel"))
print("Nilai untuk 'pisang':", ht.search("pisang"))

"""2. Penanganan Collision dengan Linear Probing"""

class LinearProbingHashTable:
  def __init__(self, size):
    self.size = size
    self.table = [None] * size

  def hash_function(self, key):
    return hash(key) % self.size

  def insert(self, key, value):
    index = self.hash_function(key)
    original_index = index

    while self.table[index] is not None:
      if self.table[index] [0] == key:
        break
      index = (index + 1) % self.size
      if index == original_index:
        raise Exception("Hash table penuh")

    self.table[index] = (key, value)

  def search(self, key):
    index = self.hash_function(key)
    original_index = index

    while self.table[index] is not None:
      if self.table[index] [0] == key:
        return self.table[index] [1]
      index = (index + 1) % self.size
      if index == original_index:
        break
    return None

ht = LinearProbingHashTable(5)
ht.insert ("apel", 100)
ht.insert("pisang", 200)
ht.insert("melon", 300)

print("Nilai untuk 'apel':", ht.search("apel"))
print("Nilai untuk 'melon':", ht.search("melon"))

"""3. Penanganan Collision dengan Chaining"""

class ChainingHashTable:
  def __init__(self, size):
    self.size = size
    self.table = [[] for _ in range(size)]

  def hash_function(self, key):
    return hash(key) % self.size

  def insert(self, key, value):
    index = self.hash_function(key)
    for i, (k, v) in enumerate(self.table[index]):
      if k == key:
        self.table[index][i] = (key, value)
        return
    self.table[index].append((key, value))

  def search(self, key):
    index = self.hash_function(key)
    for k, v in self.table[index]:
      if k == key:
        return v
    return None

ht = ChainingHashTable(5)
ht.insert("apel", 100)
ht.insert("pisang", 200)
ht.insert("melon", 300)
print("Nilai untuk 'apel':", ht.search("apel"))
print("Nilai untuk 'melon':", ht.search("melon"))

"""### D. LATIHAN /TUGAS

1. Eksperimen Sederhana Linear Probing
"""

class LinearProbingHashTable:
    def __init__(self, size):
        self.size = size
        self.table = [None] * size

    def hash_function(self, key):
        return hash(key) % self.size

    def insert(self, key, value):
        index = self.hash_function(key)
        original_index = index

        while self.table[index] is not None:
            if self.table[index][0] == key:
                break
            index = (index + 1) % self.size
            if index == original_index:
                raise Exception("Hash table penuh")

        self.table[index] = (key, value)

    def search(self, key):
        index = self.hash_function(key)
        original_index = index

        while self.table[index] is not None:
            if self.table[index][0] == key:
                return self.table[index][1]
            index = (index + 1) % self.size
            if index == original_index:
                break
        return None

ht_LPHT = LinearProbingHashTable(5)

ht_LPHT.insert("A", 10)
ht_LPHT.insert("B", 20)
ht_LPHT.insert("C", 30)
ht_LPHT.insert("D", 40)
ht_LPHT.insert("E", 50)

print(ht_LPHT.table)

"""2. Percobaan Dasar Chaining"""

class ChainingHashTable:
    def __init__(self, size):
        self.size = size
        self.table = [[] for _ in range(size)]

    def hash_function(self, key):
        return hash(key) % self.size

    def insert(self, key, value):
        index = self.hash_function(key)
        for i, (k, v) in enumerate(self.table[index]):
            if k == key:
                self.table[index][i] = (key, value)
                return
        self.table[index].append((key, value))

    def search(self, key):
        index = self.hash_function(key)
        for k, v in self.table[index]:
            if k == key:
                return v
        return None

ht_CHT = ChainingHashTable(3)

ht_CHT.insert("apel", 100)
ht_CHT.insert("melon", 200)
ht_CHT.insert("lemon", 300)
ht_CHT.insert("pisang", 400)

print("Isi tabel (Chaining):")
for i, bucket in enumerate(ht_CHT.table):
    print(f"slot {i}:{bucket}")